# Generated by Django 5.0.4 on 2024-04-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidBackendAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.IntegerField(unique=True)),
                ('videosId', models.CharField(max_length=255)),
                ('timer', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('isplaying', models.BooleanField()),
                ('issharing', models.BooleanField()),
                ('istrue', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
