# Generated by Django 5.0.4 on 2024-04-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidBackendAPI', '0002_videos_alter_user_email_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='videoslink',
            field=models.CharField(default='', max_length=255),
        ),
    ]
