# Generated by Django 5.0.4 on 2024-04-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidBackendAPI', '0003_videos_videoslink'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.IntegerField()),
                ('username', models.CharField(max_length=256, null=True, unique=True)),
                ('identifiant', models.IntegerField()),
                ('money', models.IntegerField(default=0)),
                ('howmanydoyoushare', models.IntegerField(default=0)),
                ('howmanydoyouviews', models.IntegerField(default=0)),
                ('howmanydoyouparrainage', models.IntegerField(default=0)),
            ],
        ),
    ]
