# Generated by Django 5.0.4 on 2024-05-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidBackendAPI', '0004_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videosname', models.CharField(max_length=256)),
                ('idvideos', models.CharField(max_length=256)),
                ('timerboolean', models.BooleanField()),
            ],
        ),
    ]
