# Generated by Django 5.0.4 on 2024-06-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidBackendAPI', '0006_career_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=256)),
                ('TilteName', models.CharField(max_length=256)),
                ('parentAdresseName', models.CharField(max_length=256)),
                ('BaseName', models.CharField(max_length=256)),
                ('Miniaturename', models.CharField(max_length=256)),
                ('MparentAdresseName', models.CharField(max_length=256)),
                ('MBaseName', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='career',
            name='contratEnCours',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='career',
            name='contratRenouvelable',
            field=models.BooleanField(default=False),
        ),
    ]
