# Generated by Django 5.0.4 on 2024-06-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidBackendAPI', '0007_uploadvideo_alter_career_contratencours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialaccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=256)),
                ('ismonetised', models.BooleanField()),
                ('nameyoutube', models.CharField(max_length=256)),
                ('nbrSub', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
