# Generated by Django 5.0.4 on 2024-06-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidBackendAPI', '0009_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addBy', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('urlChannel', models.CharField(max_length=256)),
                ('ChannelId', models.CharField(max_length=256)),
            ],
        ),
    ]
