# Generated by Django 5.0.4 on 2024-07-03 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidBackendAPI', '0012_mission_missionbut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='EndMissionDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 2, 2, 23, 4, 187442, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='mission',
            name='MissionDate',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 2, 23, 4, 187442, tzinfo=datetime.timezone.utc)),
        ),
    ]
